### ISSUE TITLE
Error when running python demo

### ISSUE THREAD

**Issue by Clunx** [Picovoice/leopard#10]
when running the python demo I have this error that pop out.
I have made sure to use the whole folder as given on the github and to include my licence file:

Traceback (most recent call last):
  File "demo/python/leopard_demo.py", line 61, in <module>
    license_path=args.license_path)
  File "demo/python\../../binding/python\leopard.py", line 54, in __init__
    self._libc = CDLL(find_library('c'))
  File "C:\Users\parth\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

**Comment by Clunx** [comment]
I've fixed it thank you

**Comment by Palanikumar1611** [comment]
> I've fixed it thank you

I am also having the same issue, could please let me know how you resolved it
