### ISSUE TITLE
Leopard Issue: Error trying to run demo on windows 10

### ISSUE THREAD

**Issue by ricardoborges** [Picovoice/leopard#192]
windows 10
node v8.11.3
npm 5.6.0

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cheetah-web-demo@1.0.0~prestart: cheetah-web-demo@1.0.0
6 info lifecycle cheetah-web-demo@1.0.0~start: cheetah-web-demo@1.0.0
7 verbose lifecycle cheetah-web-demo@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle cheetah-web-demo@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Ricardo\git\leopard\demo\web\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Tools\ffmpeg\bin;C:\Program Files (x86)\Calibre2\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft VS Code\bin;C:\HaxeToolkit\haxe\;C:\HaxeToolkit\neko;C:\Program Files (x86)\dotnet\;C:\Program Files\PuTTY\;C:\ProgramData\UNIVALI\Portugol Studio;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Ricardo\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\Ricardo\AppData\Local\Programs\Python\Python311\;C:\Users\Ricardo\.cargo\bin;C:\Users\Ricardo\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Ricardo\AppData\Local\Programs\Python\Python36-32\;C:\Users\Ricardo\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\MongoDB\Server\3.4\bin;C:\Program Files\Heroku\bin;C:\Users\Ricardo\AppData\Roaming\npm;C:\Tools\C3PO;;C:\Users\Ricardo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Ricardo\.dotnet\tools
9 verbose lifecycle cheetah-web-demo@1.0.0~start: CWD: C:\Ricardo\git\leopard\demo\web
10 silly lifecycle cheetah-web-demo@1.0.0~start: Args: [ '/d /s /c', 'yarn run http-server -a localhost -p 5000' ]
11 silly lifecycle cheetah-web-demo@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle cheetah-web-demo@1.0.0~start: Failed to exec start script
13 verbose stack Error: cheetah-web-demo@1.0.0 start: `yarn run http-server -a localhost -p 5000`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cheetah-web-demo@1.0.0
15 verbose cwd C:\Ricardo\git\leopard\demo\web
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error cheetah-web-demo@1.0.0 start: `yarn run http-server -a localhost -p 5000`
22 error Exit status 1
23 error Failed at the cheetah-web-demo@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mrrostam** [comment]
You need `Node.js 14+` as mentioned in the [doc](https://picovoice.ai/docs/quick-start/leopard-web/).

**Comment by ricardoborges** [comment]
Thanks!
