### ISSUE TITLE
Leopard Issue:  Demo doesn't run

### ISSUE THREAD

**Issue by drewdelano** [Picovoice/leopard#342]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Leopard docs
- [X] I have searched the existing issues for Leopard

### SDK

.NET

### Leopard package version

2.0.1

### Framework version

.NET 8.0

### Platform

Windows (x86_64)

### OS/Browser version

N/A

### Describe the bug

```
Pv.LeopardActivationLimitException: Leopard init failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `0000012C`)
   at Pv.Leopard..ctor(String accessKey, String modelPath, Boolean enableAutomaticPunctuation, Boolean enableDiarization)
   at Pv.Leopard.Create(String accessKey, String modelPath, Boolean enableAutomaticPunctuation, Boolean enableDiarization)
   at LeopardDemo.MicDemo.RunDemo(String accessKey, String modelPath, Boolean enableAutomaticPunctuation, Boolean enableDiarization, Boolean verbose, Int32 audioDeviceIndex) in C:\git\picovoice\leopard\demo\dotnet\LeopardDemo\MicDemo.cs:line 59
   at LeopardDemo.MicDemo.Main(String[] args) in C:\git\picovoice\leopard\demo\dotnet\LeopardDemo\MicDemo.cs:line 249
```

### Steps To Reproduce

1. Open project
2. Switch "StartupObject" to "LeopardDemo.MicDemo"
3. Switch Framework version to net8.0 (net6.0 was LTS, but the support has lapsed)
4. Run the project

### Expected Behavior

Demo runs.  This previously worked before the 2.* upgrade.

**Comment by laves** [comment]
A `LeopardActivationLimitException` means that you have run out of your 30-day usage allowance. You can confirm this by checking your Picovoice Console dashboard.

**Comment by laves** [comment]
Close due to inactivity

**Comment by drewdelano** [comment]
I suspect that's probably the issue, but the exception doesn't say that

**Comment by drewdelano** [comment]
Ah ok.  I was focusing too much on the memory address stuff.
